org.gradle.jvmargs=-Xmx2G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_id=interactentity
mod_name=Interact Entity
mod_license=MIT
mod_version=2.2.2-1.20.1
mod_group_id=net.ashpapi.interactentity
mod_authors=AshPapi
mod_description=Dialogue system for Minecraft entities. Create interactive dialogues with mobs using JSON.
